### ISSUE TITLE
Question about "Turns-aware Aggregation"

### ISSUE THREAD

**Issue by betterenvi** [cooelf/DeepUtteranceAggregation#2]
#### Question about "Turns-aware Aggregation"

It is a bit strange that you concatenate the representation of each utterance/response and the last utterance along the last axis (https://github.com/cooelf/DeepUtteranceAggregation/blob/master/main.py#L327).
Can you give some explanations?

Ps.
If I did not misunderstand your idea,  you concatenate the representation of each utterance/response (S_j = [h_{j,1}, h_{j,2}, ..., h_{j,n}]) and the last utterance (S_t = [h_{t,1}, h_{t,2}, ..., h_{t,n}]). What we get is [[h_{j,1}, h_{t,1}], [h_{j,2}, h_{t,2}], ..., [h_{j,n}, h_{t,n}]].
That is, the representations at same timestep is concatenated as one vector. I don't think it is reasonable, since it means little that two words from two distinct sentences are at the same timestep.

**Comment by cooelf** [comment]
Since there might be long-term information loss in RNNs, we hope to preserve the information as many as possible after the GRU encoding (for subsequent attention-based key information extraction).  The GRU output could be regarded as the overall utterance representation. Please note that, each timestep of GRU output contains the successive information of previous timesteps , instead of simply the concatenation of two words. 

Meanwhile, to evaluate the performance of element-wise summation and element-wise  multiplication (we found element-wise mul work effectively in MRC embedding encoding), it is neccessary to intergate the vectors in element-wise manner.
